export enum FormItemTypeEnum {
  INPUT = 'INPUT',
  INPUT_NUMBER = 'INPUT_NUMBER',
  PASSWORD = 'PASSWORD',
  TEXTAREA = 'TEXTAREA',
  CHECKBOX = 'CHECKBOX',
  CHECKBOX_GROUP = 'CHECKBOX_GROUP',
  SELECT = 'SELECT',
  RADIO = 'RADIO',
  RADIO_GROUP = 'RADIO_GROUP',
  TIME_PICKER = 'TIME_PICKER',
  DATE_PICKER = 'DATE_PICKER'
}
